spring:
  datasource:
    url: jdbc:postgresql://dpg-cnthl3la73kc738i8btg-a/cardinal
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
