name: develop
on:
  push:
    branches: [ develop ]
jobs:
  test:
    name: test
    permissions:
      packages: read
    uses: ./.github/workflows/step-test.yaml
    secrets:
      GPR_USER:
        required: true
      GPR_KEY:
        required: true
