name: develop
on:
  push:
    branches: [ develop ]
env:
  GPR_USER: ${{ secrets.GPR_USER }}
  GPR_KEY: ${{ secrets.GPR_KEY }}
jobs:
  test:
    name: test
    permissions:
      packages: read
    uses: ./.github/workflows/step-test.yaml
